### ISSUE TITLE
calcTGIF error

### ISSUE THREAD

**Issue by legeinei123** [rikenbit/scTGIF#1]
calcTGIF(assay(sce, 'logcounts')) gives me the following error:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘calcTGIF’ for signature ‘"matrix"’

Subsetting the assay separately doesn't solve the error. Have you encountered it before? 

Thanks

**Comment by kokitsuyuzaki** [comment]
To reproduce the error in my environment, please provide the following items.

1. Minimum dataset
2. Source-code
3. Environment information: e.g. `sessionInfo()`
